kind: pipeline
name: default

steps:
  - name: node modules
    image: node:12
    commands:
    - npm install --no-progress --quiet --unsafe-perm > npm-install.log

  - name: tslint
    image: node:12
    commands:
    - npm run tslint
    - npm run prettify

  - name: jest
    image: node:12
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
    - npm run jest

  - name: build
    image: node:12
    commands:
    - npm run build
